# -*- coding: utf-8 -*-

from django.conf.urls.defaults import patterns, url
from circuits.api import resources


urlpatterns = patterns('',
    url(
        r'^circuits/?$',
        resources.CircuitCollection.as_view(),
        name='circuit_collection_resource'
    ),
    url(
        r'^circuits/create/?$',
        resources.CircuitCreationController.as_view(),
        name='circuit_creation_controller_resource'
    ),
    url(
        r'^circuits/(?P<circuit_id>[\d]+)/update/?$',
        resources.CircuitUpdateController.as_view(),
        name='circuit_update_controller_resource'
    ),
    url(
        r'^circuits/(?P<circuit_id>[\d]+)/patch/?$',
        resources.CircuitPatchController.as_view(),
        name='circuit_patch_controller_resource'
    ),
    url(
        r'^circuits/(?P<circuit_id>[\d]+)/stops/(?P<stop_id>[\d]+)$',
        resources.CircuitStopResource.as_view(),
        name='circuit_stop_resource'
    ),
    url(
        r'^circuits/categories/?$',
        resources.CircuitCategoryCollection.as_view(),
        name='circuit_category_collection_resource'
    ),
    url(
        r'^circuits/categories/(?P<category_slug>[\w_-]+)$',
        resources.CircuitCategoryResource.as_view(),
        name='circuit_category_resource'
    ),
    url(
        r'^circuits/(?P<circuit_id>[\d]+)$',
        resources.CircuitResource.as_view(),
        name='circuit_resource'
    ),
    url(
        r'^circuits/(?P<circuit_id>[\d]+)/upload_picture/?$',
        resources.CircuitPictureController.as_view(),
        name='circuit_picture_controller'
    ),
    url(
        r'^circuits/(?P<circuit_id>[\d]+)/stops/create/?$',
        resources.CircuitStopCreationController.as_view(),
        name='circuit_stop_creation_controller_resource'
    ),
    url(
        r'^circuits/(?P<circuit_id>[\d]+)/stops/(?P<place_id>[\d+])/update/?$',
        resources.CircuitStopUpdateController.as_view(),
        name='circuit_stop_update_controller_resource'
    ),
    url(
        r'^circuits/(?P<circuit_id>[\d]+)/published/?$',
        resources.CircuitPublicationStatusFunction.as_view(),
        name='circuit_publication_status_function_resource'
    ),
    url(
        r'^circuits/(?P<circuit_id>[\d]+)/change_publication_status/?$',
        resources.CircuitPublicationStatusController.as_view(),
        name='change_publication_status_controller_resource'
    ),
    url(
        r'^circuits/(?P<circuit_id>[\d]+)/publish_circuit/?$',
        resources.CircuitPublishController.as_view(),
        name='publish_circuit_controller_resource'
    ),
    url(
        r'^circuits/(?P<circuit_id>[\d]+)/unpublish_circuit/?$',
        resources.CircuitUnpublishController.as_view(),
        name='unpublish_circuit_controller_resource'
    ),
        url(
        r'^circuits/(?P<circuit_id>[\d]+)/is_favorite/?$',
        resources.IsFavoriteFunction.as_view(),
        name='is_favorite_function_resource'
    ),
    url(
        r'^circuits/(?P<circuit_id>[\d]+)/add_favorite/?$',
        resources.AddFavoriteController.as_view(),
        name='add_favorite_controller_resource'
    ),
     url(
        r'^circuits/(?P<circuit_id>[\d]+)/remove_favorite/?$',
        resources.RemoveFavoriteController.as_view(),
        name='remove_favorite_controller_resource'
    ),
     #  UPVOTE AND DOWNVOTE
    url(
        r'^circuits/(?P<circuit_id>[\d]+)/upvote/?$',
        resources.UpvoteController.as_view(),
        name='upvote_controller_resource'
    ),
    url(
        r'^circuits/(?P<circuit_id>[\d]+)/downvote/?$',
        resources.DownvoteController.as_view(),
        name='downvote_controller_resource'
    ),
    url(
        r'^circuits/(?P<circuit_id>[\d]+)/vote/?$',
        resources.VoteController.as_view(),
        name='vote_controller_resource'
    ),
    #  CATEGORY FOLLOW
    url(
        r'^circuits/categories/(?P<category_slug>[\w_-]+)/is_following/?$',
        resources.IsFollowingCategoryFunction.as_view(),
        name='is_following_category_function_resource'
    ),
    url(
        r'^circuits/categories/(?P<category_slug>[\w_-]+)/follow/?$',
        resources.FollowCategoryController.as_view(),
        name='follow_category_controller_resource'
    ),
    url(
        r'^circuits/categories/follow_set/?$',
        resources.SetFollowCategoriesController.as_view(),
        name='set_follow_categories_controller_resource'
    ),
    url(
        r'^circuits/categories/(?P<category_slug>[\w_-]+)/unfollow/?$',
        resources.UnfollowCategoryController.as_view(),
        name='unfollow_category_controller_resource'
    ),
    #   REMIX
    url(r'^circuits/(?P<circuit_id>[\d]+)/remix/?$',
        resources.CircuitRemixController.as_view(),
        name='remix_circuit_controller_resource'
    ),
    url(
        r'^circuits/(?P<circuit_id>[\d]+)/post-comment/?$',
        resources.CircuitPostCommentController.as_view(),
        name='post_comment_controller_resource'
    ),
)
