# -*- coding: utf-8 -*-

from django.conf.urls.defaults import patterns, url


urlpatterns = patterns('circuits.views',
    url(r'^create/$',
        'create_circuit',
        name='circuit_create',
    ),
    url(r'^(?P<circuit_id>\d+)/adult_content_agreement/$',
        'adult_content_agreement',
        name='adult_content_agreement',
    ),
    url(r'^(?P<circuit_id>\d+)/adult_content_agreement/agree/$',
        'adult_content_agreement_agree',
        name='adult_content_agreement_agree',
    ),
    url(r'^(?P<circuit_id>\d+)/edit/$',
        'edit_circuit',
        name='circuit_edit',
    ),
    url(r'^(?P<circuit_id>\d+)/delete/$',
        'delete_circuit',
        name='circuit_delete',
    ),
    url(r'^categories/(?P<category_slug>[\w_-]+)/(?P<gmac_slug>[\/\w_-]+)/$',
        'circuit_category_listing',
        name='circuit_category_listing_loc',
    ),
    url(r'^categories/(?P<category_slug>[\w_-]+)/$',
        'circuit_category_listing',
        name='circuit_category_listing',
    ),
    url(r'^categories/$',
        'set_favorite_cats',
        name='set_favorite_cats',
    ),
    # FIXME: Este url deberia de estar en user_profile
    url(r'^list/myroutes/$',
        'my_circuits_list_view',
        name='mycircuits',
    ),
    url(r'^(?P<circuit_id>\d+)/$',
        'circuit_detail',
        name='circuit_detail_without_slug',
    ),
    url(r'^(?P<circuit_id>\d+)/(?P<slug>[\w_-]+)/$',
        'circuit_detail',
        name='circuit_detail_with_slug',
    ),
    url(r'^(?P<circuit_id>\d+)/remix$',
        'remix_circuit',
        name='remix_circuit',
    ),
    url(r'^stop/(?P<stop_id>\d+)/$',
        'stop_detail',
        name='stop_detail',
    ),
    url(r'^stop/(?P<stop_id>\d+)/edit$',
        'stop_edit',
        name='stop_edit',
    ),
    url(r'^stop/(?P<stop_id>\d+)/delete$',
        'stop_delete',
        name='stop_delete',
    ),
)
